"""Plain-English write-ups of tool results, for the local analyst.

Each function takes the same compact JSON payload Claude would see and returns
markdown. The wording follows the copilot's rules: numbers only from results,
no price predictions, and a sceptical reading of every backtest.
"""

from __future__ import annotations

import math
from typing import Any

SECONDS_PER_YEAR = 365 * 24 * 3600
CATEGORY_NAMES = {
    "volatility": "Volatility indices",
    "jump": "Jump",
    "crash_boom": "Crash/Boom",
    "step": "Step",
    "regime": "Regime switching",
    "momentum": "Momentum",
}


def pct(x: float | None, digits: int = 2, signed: bool = False) -> str:
    if x is None or not math.isfinite(x):
        return "n/a"
    s = f"{x * 100:.{digits}f}%"
    return f"+{s}" if signed and x > 0 else s


def vol(x: float | None) -> str:
    return pct(x, 1)


def duration(minutes: float | None) -> str:
    if minutes is None:
        return "n/a"
    if minutes < 90:
        return f"{round(minutes)} min"
    hours = minutes / 60
    return f"{hours:.1f} h" if hours < 48 else f"{hours / 24:.1f} days"


def ago(epoch: int, now: int) -> str:
    minutes = max(0, now - epoch) / 60
    if minutes < 1:
        return "under a minute ago"
    if minutes < 90:
        return f"{round(minutes)} min ago"
    return f"{minutes / 60:.1f} h ago"


def ordinal(n: float) -> str:
    n = int(round(n))
    suffix = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def article(label: str) -> str:
    """'an' before labels read with a vowel sound: SMA (es), RSI (ar), 8-, 11-, 18-bar."""
    return "an" if label[:1] in "AEIOUaeiouRS8" or label.startswith(("11", "18")) else "a"


def strategy_label(spec: dict[str, Any]) -> str:
    sig = spec["signal"]
    if sig["type"] == "sma_cross":
        label = f"SMA {sig['fast']}/{sig['slow']} crossover"
    elif sig["type"] == "rsi":
        mode = "momentum" if sig.get("mode") == "momentum" else "mean-reversion"
        label = f"RSI({sig.get('period', 14)}) {mode} {sig.get('lower', 30):g}/{sig.get('upper', 70):g}"
    else:
        label = f"{sig['lookback']}-bar breakout"
    extras = []
    if spec.get("direction") == "long_only":
        extras.append("long only")
    elif spec.get("direction") == "short_only":
        extras.append("short only")
    if spec.get("stop_loss_pct"):
        extras.append(f"{spec['stop_loss_pct']:g}% stop")
    if spec.get("take_profit_pct"):
        extras.append(f"{spec['take_profit_pct']:g}% target")
    return label + (f" ({', '.join(extras)})" if extras else "")


def _bars(d: dict[str, Any]) -> str:
    g = d.get("granularity_s") or 0
    unit = "ticks" if not g else f"{g // 60}-minute candles" if g % 60 == 0 else f"{g}s candles"
    return f"{d['bars']:,} {unit}"


# ------------------------------------------------------------------ per tool


def symbols(d: dict[str, Any]) -> str:
    groups: dict[str, list[str]] = {}
    for row in d["symbols"]:
        groups.setdefault(row["category"], []).append(f"**{row['symbol']}**")
    lines = [f"There are {len(d['symbols'])} simulated indices, each generated by a known random process:", ""]
    lines += [f"- {CATEGORY_NAMES.get(cat, cat)}: {', '.join(names)}" for cat, names in groups.items()]
    lines += ["", "Pick one on the chart or ask me about any of them, for example *\"how volatile is JUMP50?\"*."]
    return "\n".join(lines)


def prices(d: dict[str, Any]) -> str:
    move = d["change_pct"] / 100
    direction = "up" if move > 0 else "down" if move < 0 else "flat"
    return (
        f"**{d['symbol']}** is {direction} **{pct(move, 3, signed=True)}** over the last {duration(d['minutes'])} "
        f"({d['points']:,} {'ticks' if not d['granularity_s'] else 'candles'}), trading between "
        f"{d['low']:,.2f} and {d['high']:,.2f}. Moves like this are what a random process produces; they don't "
        "say anything about where it goes next."
    )


def volatility(d: dict[str, Any], now: int) -> str:
    rv, design = d["realized_vol"], d.get("design_vol")
    head = f"**{d['symbol']}** has run at **{vol(rv)}** annualised volatility over the last {duration(d['minutes'])}"
    if design:
        gap = rv / design - 1
        if abs(gap) < 0.1:
            head += f", in line with its {vol(design)} design"
        else:
            head += f", {'above' if gap > 0 else 'below'} its {vol(design)} design"
            if gap > 0 and d["jumps"]["count"]:
                head += " because the jumps add to the diffusion volatility"
    parts = [head + "."]

    pctl = d["current_percentile"]
    mood = "quieter than usual" if pctl < 20 else "elevated" if pctl > 80 else "about normal"
    parts.append(
        f"Right now ({d['window']}-tick window) it's at **{vol(d['current_rolling_vol'])}**, the {ordinal(pctl)} "
        f"percentile of this sample: {mood}."
    )
    g = d.get("garch")
    if g:
        persistent = " Volatility shocks here are persistent." if g["persistence"] > 0.95 and g["alpha"] > 0.02 else ""
        parts.append(f"A GARCH(1,1) fit expects about **{vol(g['forecast_vol'])}** over the next {g['horizon_periods']} ticks.{persistent}")

    jumps = d["jumps"]
    if jumps["count"]:
        largest = d.get("largest_move")
        where = f", the largest a **{pct(largest['log_return'], 3, signed=True)}** move {ago(largest['epoch'], now)}" if largest else ""
        parts.append(f"I found **{jumps['count']} jump{'s' if jumps['count'] != 1 else ''}** bigger than {jumps['threshold_sigma']:g} robust standard deviations{where}.")
    else:
        parts.append("No jumps: every move stayed within the normal range for this index.")
    return " ".join(parts)


def regime(d: dict[str, Any]) -> str:
    share = d["time_share"]
    if share["normal"] >= 0.95:
        return (
            f"**{d['symbol']}** shows a single volatility regime. Rolling volatility stayed within the "
            f"±{d['noise_band_pct']:.0f}% band that sampling noise explains for {share['normal']:.0%} of the last "
            f"{duration(d['minutes'])}, so any apparent calm or turbulent spells are noise."
        )
    return (
        f"**{d['symbol']}** is currently **{d['current_regime']}** ({vol(d['current_vol'])} against a "
        f"{vol(d['median_vol'])} median). Over the last {duration(d['minutes'])} it was calm {share['calm']:.0%} of the "
        f"time, normal {share['normal']:.0%} and turbulent {share['turbulent']:.0%}, switching {d['n_switches']} times. "
        f"Those swings are larger than the ±{d['noise_band_pct']:.0f}% sampling-noise band, so the regimes are real."
    )


def compare(d: dict[str, Any]) -> str:
    rows = d["sorted_calmest_first"]
    fmt = lambda r: f"**{r['symbol']}** ({vol(r['current_vol'])})"  # noqa: E731
    if len(rows) <= 4:
        ranking = ", then ".join(fmt(r) for r in rows)
        text = f"Calmest to most volatile right now: {ranking}."
    else:
        text = (
            f"Calmest right now: {', '.join(fmt(r) for r in rows[:3])}. "
            f"Most volatile: {', '.join(fmt(r) for r in rows[::-1][:3])}."
        )
    off = [r for r in rows if r.get("design_vol") and abs(r["current_vol"] / r["design_vol"] - 1) > 0.3]
    if off:
        names = ", ".join(f"{r['symbol']} ({vol(r['current_vol'])} vs {vol(r['design_vol'])} design)" for r in off[:3])
        text += f" Readings use a short {d['window']}-tick window, so they wander; the biggest gaps from design are {names}."
    else:
        text += f" Every index with a design volatility is reading close to it (short {d['window']}-tick window)."
    return text


def backtest(d: dict[str, Any], spec: dict[str, Any]) -> str:
    null = d["null_test"]
    p = null["p_value"]
    p_str = "p < 0.002" if p <= 0.002 else f"p = {p:.3f}"
    oos = d["out_of_sample"]
    lines = [
        f"**{strategy_label(spec)}** on **{d['symbol']}** ({_bars(d)}, fees {d['fee_bps']:g} bp):",
        "",
        f"- Net return **{pct(d['full']['total_return'], 2, True)}** against buy-and-hold "
        f"{pct(d['buy_and_hold_return'], 2, True)}, max drawdown {pct(d['full']['max_drawdown'])}. "
        f"{d['n_trades']:,} trades, {pct(d['win_rate'], 0)} winners.",
        f"- Timing test: {p_str}. "
        + (
            "The entry timing beats randomly re-timed copies of the same trades."
            if p < 0.05
            else "Randomly re-timed copies of the same trades did as well, so the timing shows no skill."
        ),
        f"- Out-of-sample (last 30%): {pct(oos['total_return'], 2, True)}.",
        "",
        f"**Verdict:** {d['verdict']}",
    ]
    return "\n".join(lines)


def walk_forward(d: dict[str, Any], spec: dict[str, Any]) -> str:
    chosen = ", ".join(
        "/".join(str(v) for k, v in f["chosen_params"].items() if k != "mode") for f in d["folds"]
    )
    oos = d["out_of_sample"]
    return (
        f"Walk-forward on **{d['symbol']}** ({d['signal_type'].replace('_', ' ')}, {d['grid_size']} parameter sets, "
        f"{d['n_folds']} folds). The optimiser picked {chosen} on successive training windows. In-sample Sharpe "
        f"averaged **{d['mean_in_sample_sharpe']:.2f}**; out-of-sample it was **{oos['sharpe']:.2f}**, a "
        f"{pct(oos['total_return'], 2, True)} return.\n\n**Verdict:** {d['verdict']}"
    )


def one_hour_range(annual_vol: float, price: float) -> str:
    sigma = annual_vol * math.sqrt(3600 / SECONDS_PER_YEAR)
    return (
        f"At {vol(annual_vol)} annualised volatility, a typical one-hour move is about **±{pct(sigma)}** "
        f"(±{price * sigma:,.2f} points from {price:,.2f}), and about 95% of hours should stay within ±{pct(2 * sigma)}."
    )


PREDICTION_PREFACE = (
    "I can't tell you which way it will go, and no one can: every index here is generated by a random "
    "process, so past prices carry no information about direction. What I can measure is how far it's "
    "likely to move."
)

HELP = """I'm the local analyst: I run the quant tools on the simulated market and explain the results, no API key needed. Try:

- *"How volatile is VOL75 compared with its design?"*
- *"Which index is calmest right now?"*
- *"Does REGIME have distinct volatility regimes?"*
- *"Backtest a 20/50 SMA crossover on VOL75 with a 1% stop"*
- *"Is there an edge on MOMENTUM50 with a fast SMA crossover and zero fees?"*
- *"Optimise a breakout on VOL50 with walk-forward"*

Strategies I can test: SMA crossovers, RSI thresholds (mean-reversion or momentum) and channel breakouts, with long/short filters, stop-loss, take-profit and fees."""


def unsupported(name: str, closest: str, example: str, symbol: str) -> str:
    return (
        f"{name[0].upper() + name[1:]} isn't in my strategy toolkit. I can backtest SMA crossovers, RSI thresholds "
        f"and channel breakouts, with direction filters, stop-loss, take-profit and fees. The closest match is "
        f"{article(closest)} {closest}; try *\"backtest {example} on {symbol}\"*."
    )
